Raj/bad pv/drop sys with only nan
openclimatefix/ocf_datapipes pull request #131
Opened 2022-12-28 14:31 UTC by vrym2

# Pull Request

## Description

This PR deals with the function that drops the systems which have only `NaN's` in a given single day. This PR incorporates #129 in its tests

Fixes #

## How Has This Been Tested?

The test has been performed on `passiv_datapipe1 and `pvoutput_datapipe`. It has also been tested with a constructed `xarray` where the `xarray` has three systems with one system only containing `NaN's`. After the test, the result `xarray` drops the system with only `NaN's`
- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

2023-01-04 11:29 UTC, jacobbieker requested changes
This looks good overall! Just a few changes to make a bit clearer, but looks good overall

2023-01-04 11:29 UTC, jacobbieker commented on ocf_datapipes/utils/utils.py
> +def return_sys_indices_which_has_cont_nan(arr: np.ndarray, check_interval: int = 287) -> np.ndarray:
```suggestion
def return_system_indices_which_has_contiguous_nan(arr: np.ndarray, check_interval: int = 287) -> np.ndarray:
```

Could the names of the functions be more explicit? Not sure if this should be contiguous or continuous, or something else, but just to keep it as explicit as possible

2023-01-04 11:29 UTC, jacobbieker commented on ocf_datapipes/utils/utils.py
> +    number_of_sys = arr.shape[1]
```suggestion
    number_of_systems = arr.shape[1]
```

2023-01-04 11:44 UTC, vrym2 commented on ocf_datapipes.code-workspace
> +{
sure, I'll add this .gitignore!

2023-01-04 12:01 UTC, vrym2 commented on ocf_datapipes/select/drop_pv_sys_with_only_nan_in_a_day.py
> +
ok!

2023-01-04 14:33 UTC, peterdudfield commented on ocf_datapipes/select/drop_pv_sys_with_only_nan_in_a_day.py
> +    """Remove any PV systems with less than 1 day of data"""
need to update text

2023-01-05 16:47 UTC, vrym2 commented on ocf_datapipes/select/drop_pv_sys_with_only_nan_in_a_day.py
> +                for i in range(0, dates_array.size, self.intervals):
I have added an extra test `test_execution_time`, and tested with constructed `xarray` with `date_range` of an year, using timeit package, the time taken to run through one iteration is 0.0009 seconds.

2023-01-05 17:00 UTC, jacobbieker approved these changes
Looks good! Just update that class name and I think it's good to go.

2023-01-05 20:00 UTC, vrym2 commented on ocf_datapipes/select/drop_pv_sys_with_only_nan_in_a_day.py
> +class DropPVSysWithOnlyNanInADayIterDataPipe(IterDataPipe):
sure, I'll make the changes right away!

2023-01-05 20:11 UTC, merged